### ISSUE TITLE
How to compute whitecaps reflectance?

### ISSUE THREAD

**Issue by QiaoFeng0419** [fnemina/pyOSOAA#24]
I see your case study. Simple radiative transfer equation: 𝜌𝑡 = 𝜌𝑟 + 𝜌𝑎 + 𝜌𝑟𝑎 + 𝜌𝑔 + 𝑡𝜌𝑤. But no whitecaps reflectance included. How to compute whitecaps reflectance?

**Comment by fnemina** [comment]
[OSOAA](https://github.com/CNES/RadiativeTransferCode-OSOAA/blob/master/doc/OSOAA-V1.6_UserManual-V1.3.pdf) has no option to add automatically the reflectance for the whitecaps from the wind speed. However the parameter SEA.SurfAlb can be used to add a lambertian reflectance for the simulation. 

This reflectance can be calculated using different [models](http://www.oceanopticsbook.info/view/atmospheric_correction/level_2/whitecaps). This calculation can then by an input in the surfalb atribute of the SEA class in the pyOSOAA.

If you want I could create a method to do this automatically in pyOSOAA were you input the wind speed and get the corresponding surface albedo.

**Comment by QiaoFeng0419** [comment]
![图片](https://user-images.githubusercontent.com/15885479/60869486-a4af7380-a261-11e9-9ca6-3e763e5121d9.png)

**Comment by fnemina** [comment]
Hello Qiao Feng

You can the path reflectance from by subtracting the water leaving radiance from the toa radiance. I've made a jupyter notebook with an example for this. 

[PathReflectance.zip](https://github.com/fnemina/pyOSOAA/files/3382605/PathReflectance.zip)

You can also check this [here](https://github.com/fnemina/AtmosphericCorrection/issues/1).

For the diffuse transmittance, in the case where you ignore aerosols it can be approximated by the expression you wrote above. There taur is the Rayleigh Optical Thickness and the expression with the cosines is the total airmass for a plane atmosphere. It's basically the same that for the direct transmitance but the optical thickness is divided by 2. You can check it [here](http://www.oceanopticsbook.info/view/atmospheric_correction/atmospheric_transmittances) in the paragraph after equation 6. Otherwise if you consider aerosol it is more difficult to calculate.

Best regards, Fran

**Comment by QiaoFeng0419** [comment]
Thank you very much.
pyOSOAA is very useful. I love it.
